// frontend-react/src/pages/Registro.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Anchor, Button, Center, Paper, PasswordInput, Stack, Text, TextInput, Title } from '@mantine/core';
import { notifications } from '@mantine/notifications';
import { useAuth } from '../context/AuthContext';
import { extractError } from '../api/client';

export function Registro() {
  const { registrar } = useAuth();
  const navigate = useNavigate();
  const [nome, setNome] = useState('');
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [senha, setSenha] = useState('');
  const [carregando, setCarregando] = useState(false);

  async function criar() {
    if (!username || !email || !senha) {
      notifications.show({ color: 'yellow', title: 'Atenção', message: 'Preencha usuário, e-mail e senha.' });
      return;
    }
    setCarregando(true);
    try {
      await registrar(nome, username, email, senha);
      navigate('/onboarding');
    } catch (e) {
      notifications.show({ color: 'red', title: 'Ops', message: extractError(e, 'Não foi possível criar a conta.') });
    } finally {
      setCarregando(false);
    }
  }

  return (
    <Center mih="100vh">
      <Paper withBorder radius="md" p="xl" w={380}>
        <Stack gap="xs" mb="lg">
          <Title order={2}>
            zerei<Text span c="blue">.</Text>
          </Title>
          <Text c="dimmed" size="sm">Crie sua conta e comece a montar sua biblioteca.</Text>
        </Stack>
        <Stack>
          <TextInput label="Nome" placeholder="Seu nome" value={nome} onChange={(e) => setNome(e.currentTarget.value)} />
          <TextInput
            label="Usuário"
            placeholder="seu_usuario"
            autoComplete="username"
            value={username}
            onChange={(e) => setUsername(e.currentTarget.value)}
          />
          <TextInput
            label="E-mail"
            type="email"
            placeholder="voce@email.com"
            autoComplete="email"
            value={email}
            onChange={(e) => setEmail(e.currentTarget.value)}
          />
          <PasswordInput
            label="Senha"
            placeholder="mínimo 6 caracteres"
            autoComplete="new-password"
            value={senha}
            onChange={(e) => setSenha(e.currentTarget.value)}
            onKeyDown={(e) => e.key === 'Enter' && criar()}
          />
          <Button fullWidth loading={carregando} onClick={criar}>Criar conta</Button>
          <Text size="sm" ta="center">
            Já tem conta? <Anchor component={Link} to="/login">Entrar</Anchor>
          </Text>
        </Stack>
      </Paper>
    </Center>
  );
}

// frontend/src/app/pages/registro.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MessageService } from 'primeng/api';
import { AuthService } from '../core/auth.service';

@Component({
  selector: 'app-registro',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <div class="auth-wrap">
      <div class="auth-card">
        <span class="brand">zerei<span>.</span></span>
        <p class="tagline">Crie sua conta e comece a montar sua biblioteca.</p>

        <div class="field">
          <label class="label">Nome</label>
          <input class="input" [(ngModel)]="nome" placeholder="Seu nome" />
        </div>
        <div class="field">
          <label class="label">Usuário</label>
          <input class="input" [(ngModel)]="username" placeholder="seu_usuario" autocomplete="username" />
        </div>
        <div class="field">
          <label class="label">E-mail</label>
          <input class="input" type="email" [(ngModel)]="email" placeholder="voce@email.com" autocomplete="email" />
        </div>
        <div class="field">
          <label class="label">Senha</label>
          <input
            class="input"
            type="password"
            [(ngModel)]="senha"
            (keyup.enter)="criar()"
            placeholder="mínimo 6 caracteres"
            autocomplete="new-password"
          />
        </div>

        <button class="btn btn-primary btn-block" (click)="criar()" [disabled]="carregando()">
          @if (carregando()) {
            <i class="pi pi-spin pi-spinner"></i>
          } @else {
            Criar conta
          }
        </button>

        <p class="alt">Já tem conta? <a routerLink="/login">Entrar</a></p>
      </div>
    </div>
  `,
})
export class RegistroComponent {
  private auth = inject(AuthService);
  private router = inject(Router);
  private msg = inject(MessageService);

  nome = '';
  username = '';
  email = '';
  senha = '';
  carregando = signal(false);

  criar(): void {
    if (!this.username || !this.email || !this.senha) {
      this.msg.add({ severity: 'warn', summary: 'Atenção', detail: 'Preencha usuário, e-mail e senha.' });
      return;
    }
    this.carregando.set(true);
    this.auth
      .registrar({ nome: this.nome, username: this.username, email: this.email, senha: this.senha })
      .subscribe({
        next: () => this.router.navigate(['/onboarding']),
        error: (e) => {
          this.carregando.set(false);
          this.msg.add({ severity: 'error', summary: 'Ops', detail: e?.error?.erro ?? 'Não foi possível criar a conta.' });
        },
      });
  }
}
