// frontend/src/app/pages/jogo-detalhe.component.ts
import { Component, Input, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Location } from '@angular/common';
import { DialogModule } from 'primeng/dialog';
import { SelectModule } from 'primeng/select';
import { CheckboxModule } from 'primeng/checkbox';
import { MessageService } from 'primeng/api';
import { CatalogoService } from '../core/catalogo.service';
import { BibliotecaService, NovaJogatina } from '../core/biblioteca.service';
import { Jogo, UsuarioJogo } from '../core/models';
import { Plataforma } from '../core/models';
import { STATUS_LISTA, StatusJogo, statusInfo } from '../core/status';

@Component({
  selector: 'app-jogo-detalhe',
  standalone: true,
  imports: [CommonModule, FormsModule, DialogModule, SelectModule, CheckboxModule],
  template: `
    <button class="voltar" (click)="local.back()"><i class="pi pi-arrow-left"></i> Voltar</button>

    @if (jogo(); as j) {
      <div class="detalhe">
        <aside class="lado">
          <div class="capa">
            @if (j.capaUrl) {
              <img [src]="j.capaUrl" [alt]="j.nome" />
            } @else {
              <div class="ph" [style.background]="corFundo(j.nome)"><span>{{ j.nome }}</span></div>
            }
          </div>
        </aside>

        <div class="corpo">
          <h1>{{ j.nome }}</h1>
          <div class="meta">
            @if (j.ano) {
              <span>{{ j.ano }}</span>
            }
            @for (g of j.generos; track g) {
              <span class="g">{{ g }}</span>
            }
          </div>

          <!-- status -->
          <div class="bloco">
            <div class="secao-titulo">Status</div>
            <div class="status-grid">
              @for (s of statusLista; track s.valor) {
                <button
                  class="st"
                  [class.on]="uj()?.status === s.valor"
                  [style.--c]="s.cor"
                  (click)="definirStatus(s.valor)"
                >
                  <i class="pi" [ngClass]="s.icone"></i> {{ s.label }}
                </button>
              }
            </div>
          </div>

          @if (uj(); as u) {
            <!-- nota + favorito -->
            <div class="bloco linha">
              <div>
                <div class="secao-titulo">Sua nota</div>
                <div class="nota-row">
                  @for (n of dez; track n) {
                    <button class="dot" [class.on]="(u.nota ?? 0) >= n" (click)="setNota(n)">{{ n }}</button>
                  }
                  @if (u.nota) {
                    <button class="limpar-nota" (click)="setNota(0)">limpar</button>
                  }
                </div>
              </div>
              <div>
                <div class="secao-titulo">Favorito</div>
                <button class="fav" [class.on]="u.favorito" (click)="toggleFavorito()">
                  <i class="pi" [ngClass]="u.favorito ? 'pi-heart-fill' : 'pi-heart'"></i>
                </button>
              </div>
            </div>

            <!-- resenha -->
            <div class="bloco">
              <div class="secao-titulo">Resenha</div>
              <textarea
                class="input"
                rows="3"
                [(ngModel)]="resenha"
                (blur)="salvarResenha()"
                placeholder="O que você achou desse jogo?"
              ></textarea>
            </div>

            <!-- jogatinas -->
            <div class="bloco">
              <div class="jt-cab">
                <div class="secao-titulo" style="margin:0">Suas jogatinas</div>
                <button class="btn btn-ghost mini" (click)="abrirDialog()"><i class="pi pi-plus"></i> Registrar</button>
              </div>

              @if (u.jogatinas.length === 0) {
                <p class="jt-vazio">Nenhuma jogatina registrada. Marque quando e onde você jogou — inclusive rejogadas.</p>
              } @else {
                <div class="jt-lista">
                  @for (jt of u.jogatinas; track jt.id) {
                    <div class="jt">
                      <span class="jt-status" [style.background]="info(jt.status).cor + '26'" [style.color]="info(jt.status).cor">
                        <i class="pi" [ngClass]="info(jt.status).icone"></i>
                      </span>
                      <div class="jt-info">
                        <strong>{{ jt.plataforma || 'Plataforma não informada' }}</strong>
                        <span class="jt-sub">
                          {{ info(jt.status).label }}
                          @if (jt.ano) { · {{ jt.ano }} }
                          @if (jt.horas) { · {{ jt.horas }}h }
                          @if (jt.ehRejogada) { · <i class="pi pi-replay"></i> rejogada }
                        </span>
                      </div>
                      <button class="jt-del" (click)="removerJogatina(jt.id)"><i class="pi pi-trash"></i></button>
                    </div>
                  }
                </div>
              }
            </div>

            <button class="btn btn-danger" (click)="removerDaBiblioteca()" style="margin-top: 8px">
              <i class="pi pi-trash"></i> Remover da biblioteca
            </button>
          } @else {
            <p class="dica"><i class="pi pi-info-circle"></i> Escolha um status acima para adicionar este jogo à sua biblioteca.</p>
          }
        </div>
      </div>
    } @else if (carregando()) {
      <div class="vazio"><i class="pi pi-spin pi-spinner"></i><p>Carregando…</p></div>
    }

    <!-- dialog de jogatina -->
    <p-dialog header="Registrar jogatina" [(visible)]="dialogAberto" [modal]="true" [draggable]="false" [style]="{ width: '440px' }">
      <div class="form-jt">
        <div class="field">
          <label class="label">Plataforma</label>
          <p-select [options]="plataformas()" optionLabel="nome" optionValue="id" [(ngModel)]="form.plataformaId"
            placeholder="Selecione" [filter]="true" appendTo="body" styleClass="w-full" />
        </div>
        <div class="duo">
          <div class="field">
            <label class="label">Ano</label>
            <input class="input" type="number" [(ngModel)]="form.ano" placeholder="2024" />
          </div>
          <div class="field">
            <label class="label">Horas</label>
            <input class="input" type="number" [(ngModel)]="form.horas" placeholder="40" />
          </div>
        </div>
        <div class="field">
          <label class="label">Como terminou</label>
          <p-select [options]="statusLista" optionLabel="label" optionValue="valor" [(ngModel)]="form.status" appendTo="body" styleClass="w-full" />
        </div>
        <div class="chk">
          <p-checkbox [(ngModel)]="form.ehRejogada" [binary]="true" inputId="rej" />
          <label for="rej">Foi uma rejogada</label>
        </div>
      </div>
      <ng-template pTemplate="footer">
        <button class="btn btn-ghost" (click)="dialogAberto.set(false)">Cancelar</button>
        <button class="btn btn-primary" (click)="salvarJogatina()" [disabled]="salvando()">Salvar</button>
      </ng-template>
    </p-dialog>
  `,
  styles: [
    `
      .voltar {
        background: none;
        border: none;
        color: var(--text-muted);
        cursor: pointer;
        font-size: 14px;
        font-weight: 600;
        padding: 0;
        margin-bottom: 22px;
        display: inline-flex;
        gap: 8px;
        align-items: center;
      }
      .voltar:hover {
        color: var(--text);
      }
      .detalhe {
        display: grid;
        grid-template-columns: 280px 1fr;
        gap: 36px;
      }
      .lado .capa {
        position: sticky;
        top: 90px;
        border-radius: var(--radius);
        overflow: hidden;
        border: 1px solid var(--border);
        aspect-ratio: 3 / 4;
      }
      .capa img {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
      .ph {
        width: 100%;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 18px;
        text-align: center;
      }
      .ph span {
        font-weight: 800;
        font-size: 20px;
        color: rgba(255, 255, 255, 0.92);
      }
      h1 {
        font-size: 32px;
        font-weight: 800;
        letter-spacing: -0.6px;
        line-height: 1.1;
      }
      .meta {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
        margin: 14px 0 8px;
        color: var(--text-muted);
        font-size: 14px;
        align-items: center;
      }
      .meta .g {
        background: var(--surface-2);
        border: 1px solid var(--border);
        padding: 3px 10px;
        border-radius: 999px;
        font-size: 12px;
      }
      .bloco {
        margin-top: 26px;
      }
      .bloco.linha {
        display: flex;
        gap: 40px;
      }
      .status-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
        gap: 10px;
      }
      .st {
        display: flex;
        align-items: center;
        gap: 9px;
        background: var(--surface-2);
        border: 1px solid var(--border);
        color: var(--text);
        border-radius: 12px;
        padding: 12px 14px;
        font-size: 14px;
        font-weight: 600;
        cursor: pointer;
        font-family: inherit;
        transition: all 0.15s ease;
      }
      .st .pi {
        color: var(--c);
      }
      .st:hover {
        border-color: var(--border-2);
      }
      .st.on {
        border-color: var(--c);
        background: color-mix(in srgb, var(--c) 14%, var(--surface-2));
      }
      .nota-row {
        display: flex;
        gap: 5px;
        align-items: center;
        flex-wrap: wrap;
      }
      .dot {
        width: 30px;
        height: 34px;
        border-radius: 8px;
        background: var(--surface-2);
        border: 1px solid var(--border);
        color: var(--text-dim);
        cursor: pointer;
        font-weight: 700;
        font-family: inherit;
        transition: all 0.12s ease;
      }
      .dot.on {
        background: var(--gold);
        border-color: var(--gold);
        color: #1a1a1a;
      }
      .limpar-nota {
        background: none;
        border: none;
        color: var(--text-dim);
        cursor: pointer;
        font-size: 13px;
        margin-left: 6px;
      }
      .fav {
        width: 50px;
        height: 50px;
        border-radius: 12px;
        background: var(--surface-2);
        border: 1px solid var(--border);
        color: var(--text-muted);
        cursor: pointer;
        font-size: 20px;
      }
      .fav.on {
        color: var(--red);
        border-color: color-mix(in srgb, var(--red) 50%, transparent);
        background: color-mix(in srgb, var(--red) 12%, transparent);
      }
      .jt-cab {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 14px;
      }
      .mini {
        padding: 7px 12px;
        font-size: 13px;
      }
      .jt-vazio {
        color: var(--text-muted);
        font-size: 14px;
        margin: 0;
      }
      .jt-lista {
        display: flex;
        flex-direction: column;
        gap: 10px;
      }
      .jt {
        display: flex;
        align-items: center;
        gap: 13px;
        background: var(--surface);
        border: 1px solid var(--border);
        border-radius: 12px;
        padding: 12px 14px;
      }
      .jt-status {
        width: 36px;
        height: 36px;
        border-radius: 9px;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
      }
      .jt-info {
        display: flex;
        flex-direction: column;
        gap: 2px;
        flex: 1;
      }
      .jt-info strong {
        font-size: 14px;
      }
      .jt-sub {
        font-size: 13px;
        color: var(--text-muted);
      }
      .jt-del {
        background: none;
        border: none;
        color: var(--text-dim);
        cursor: pointer;
        padding: 8px;
        border-radius: 8px;
      }
      .jt-del:hover {
        color: var(--red);
        background: var(--surface-2);
      }
      .dica {
        margin-top: 22px;
        color: var(--text-muted);
        font-size: 14px;
        display: flex;
        gap: 8px;
        align-items: center;
      }
      .form-jt .duo {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 12px;
      }
      .chk {
        display: flex;
        align-items: center;
        gap: 10px;
        font-size: 14px;
        color: var(--text-muted);
      }
      :host ::ng-deep .w-full {
        width: 100%;
      }
      @media (max-width: 760px) {
        .detalhe {
          grid-template-columns: 1fr;
        }
        .lado .capa {
          max-width: 220px;
          position: static;
        }
      }
    `,
  ],
})
export class JogoDetalheComponent implements OnInit {
  @Input() id!: string;

  private catalogo = inject(CatalogoService);
  private bib = inject(BibliotecaService);
  private msg = inject(MessageService);
  local = inject(Location);

  statusLista = STATUS_LISTA;
  dez = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  info = statusInfo;

  jogo = signal<Jogo | null>(null);
  uj = signal<UsuarioJogo | null>(null);
  plataformas = signal<Plataforma[]>([]);
  carregando = signal(true);
  resenha = '';

  dialogAberto = signal(false);
  salvando = signal(false);
  form: NovaJogatina = this.formVazio();

  private get jogoId(): number {
    return Number(this.id);
  }

  ngOnInit(): void {
    this.catalogo.porId(this.jogoId).subscribe({
      next: (j) => {
        this.jogo.set(j);
        this.carregando.set(false);
      },
      error: () => this.carregando.set(false),
    });
    this.catalogo.plataformas().subscribe((p) => this.plataformas.set(p));
    this.bib.porJogo(this.jogoId).subscribe({
      next: (u) => {
        this.uj.set(u);
        this.resenha = u.resenha ?? '';
      },
      error: () => this.uj.set(null),
    });
  }

  definirStatus(status: number): void {
    this.bib.marcar(this.jogoId, status).subscribe({
      next: (u) => {
        this.uj.set(u);
        this.resenha = u.resenha ?? '';
      },
      error: (e) => this.erro(e),
    });
  }

  toggleFavorito(): void {
    const u = this.uj();
    if (!u) return;
    this.bib.atualizar(u.id, { favorito: !u.favorito }).subscribe({
      next: (atualizado) => this.uj.set({ ...atualizado, jogatinas: u.jogatinas }),
      error: (e) => this.erro(e),
    });
  }

  setNota(n: number): void {
    const u = this.uj();
    if (!u) return;
    this.bib.atualizar(u.id, { nota: n }).subscribe({
      next: (atualizado) => this.uj.set({ ...atualizado, jogatinas: u.jogatinas }),
      error: (e) => this.erro(e),
    });
  }

  salvarResenha(): void {
    const u = this.uj();
    if (!u || (u.resenha ?? '') === this.resenha) return;
    this.bib.atualizar(u.id, { resenha: this.resenha }).subscribe({
      next: (atualizado) => this.uj.set({ ...atualizado, jogatinas: u.jogatinas }),
      error: (e) => this.erro(e),
    });
  }

  abrirDialog(): void {
    this.form = this.formVazio();
    this.dialogAberto.set(true);
  }

  salvarJogatina(): void {
    const u = this.uj();
    if (!u) return;
    this.salvando.set(true);
    this.bib.adicionarJogatina(u.id, this.form).subscribe({
      next: (jt) => {
        this.uj.set({ ...u, jogatinas: [jt, ...u.jogatinas] });
        this.dialogAberto.set(false);
        this.salvando.set(false);
      },
      error: (e) => {
        this.salvando.set(false);
        this.erro(e);
      },
    });
  }

  removerJogatina(jogatinaId: number): void {
    const u = this.uj();
    if (!u) return;
    this.bib.removerJogatina(jogatinaId).subscribe({
      next: () => this.uj.set({ ...u, jogatinas: u.jogatinas.filter((x) => x.id !== jogatinaId) }),
      error: (e) => this.erro(e),
    });
  }

  removerDaBiblioteca(): void {
    const u = this.uj();
    if (!u) return;
    this.bib.remover(u.id).subscribe({
      next: () => this.uj.set(null),
      error: (e) => this.erro(e),
    });
  }

  corFundo(nome: string): string {
    let h = 0;
    for (let i = 0; i < nome.length; i++) h = nome.charCodeAt(i) + ((h << 5) - h);
    const hue = Math.abs(h) % 360;
    return `linear-gradient(150deg, hsl(${hue}, 45%, 30%), hsl(${(hue + 40) % 360}, 42%, 16%))`;
  }

  private formVazio(): NovaJogatina {
    return { plataformaId: null, ano: null, horas: null, status: StatusJogo.Zerado, ehRejogada: false, observacao: '' };
  }

  private erro(e: any): void {
    this.msg.add({ severity: 'error', summary: 'Ops', detail: e?.error?.erro ?? 'Algo deu errado.' });
  }
}

// frontend-react/src/pages/JogoDetalhe.tsx
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  ActionIcon, Badge, Button, Center, Checkbox, Group, Loader, Modal, NumberInput, Select,
  Stack, Text, Textarea, Title,
} from '@mantine/core';
import { notifications } from '@mantine/notifications';
import {
  IconArrowLeft, IconHeart, IconHeartFilled, IconInfoCircle, IconPlus, IconRepeat, IconTrash,
} from '@tabler/icons-react';
import { useJogo, usePlataformas } from '../api/catalogo';
import {
  useAdicionarJogatina, usePorJogo, useRemoverDaBiblioteca, useRemoverJogatina, useAtualizarBiblioteca, useMarcar,
  type NovaJogatina,
} from '../api/biblioteca';
import { extractError } from '../api/client';
import { StatusIcon } from '../components/StatusIcon';
import { STATUS_LISTA, StatusJogo, statusInfo } from '../types/status';

const DEZ = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

function corFundo(nome: string): string {
  let h = 0;
  for (let i = 0; i < nome.length; i++) h = nome.charCodeAt(i) + ((h << 5) - h);
  const hue = Math.abs(h) % 360;
  return `linear-gradient(150deg, hsl(${hue}, 45%, 30%), hsl(${(hue + 40) % 360}, 42%, 16%))`;
}

function formVazio(): NovaJogatina {
  return { plataformaId: null, ano: null, horas: null, status: StatusJogo.Zerado, ehRejogada: false, observacao: '' };
}

export function JogoDetalhe() {
  const { id } = useParams<{ id: string }>();
  const jogoId = Number(id);
  const navigate = useNavigate();

  const { data: jogo, isLoading } = useJogo(jogoId);
  const { data: plataformas = [] } = usePlataformas();
  const { data: ujServidor } = usePorJogo(jogoId);

  const [uj, setUj] = useState(ujServidor ?? null);
  const [resenha, setResenha] = useState('');
  const [dialogAberto, setDialogAberto] = useState(false);
  const [form, setForm] = useState<NovaJogatina>(formVazio());

  const marcar = useMarcar();
  const atualizar = useAtualizarBiblioteca();
  const adicionarJogatina = useAdicionarJogatina();
  const removerJogatina = useRemoverJogatina();
  const removerDaBiblioteca = useRemoverDaBiblioteca();

  useEffect(() => {
    setUj(ujServidor ?? null);
    setResenha(ujServidor?.resenha ?? '');
  }, [ujServidor]);

  function erro(e: unknown) {
    notifications.show({ color: 'red', title: 'Ops', message: extractError(e, 'Algo deu errado.') });
  }

  async function definirStatus(status: number) {
    try {
      const novo = await marcar.mutateAsync({ jogoId, status });
      setUj(novo);
      setResenha(novo.resenha ?? '');
    } catch (e) {
      erro(e);
    }
  }

  async function toggleFavorito() {
    if (!uj) return;
    try {
      const atualizado = await atualizar.mutateAsync({ usuarioJogoId: uj.id, body: { favorito: !uj.favorito } });
      setUj({ ...atualizado, jogatinas: uj.jogatinas });
    } catch (e) {
      erro(e);
    }
  }

  async function setNota(n: number) {
    if (!uj) return;
    try {
      const atualizado = await atualizar.mutateAsync({ usuarioJogoId: uj.id, body: { nota: n } });
      setUj({ ...atualizado, jogatinas: uj.jogatinas });
    } catch (e) {
      erro(e);
    }
  }

  async function salvarResenha() {
    if (!uj || (uj.resenha ?? '') === resenha) return;
    try {
      const atualizado = await atualizar.mutateAsync({ usuarioJogoId: uj.id, body: { resenha } });
      setUj({ ...atualizado, jogatinas: uj.jogatinas });
    } catch (e) {
      erro(e);
    }
  }

  function abrirDialog() {
    setForm(formVazio());
    setDialogAberto(true);
  }

  async function salvarJogatina() {
    if (!uj) return;
    try {
      const jt = await adicionarJogatina.mutateAsync({ usuarioJogoId: uj.id, body: form });
      setUj({ ...uj, jogatinas: [jt, ...uj.jogatinas] });
      setDialogAberto(false);
    } catch (e) {
      erro(e);
    }
  }

  async function onRemoverJogatina(jogatinaId: number) {
    if (!uj) return;
    try {
      await removerJogatina.mutateAsync(jogatinaId);
      setUj({ ...uj, jogatinas: uj.jogatinas.filter((x) => x.id !== jogatinaId) });
    } catch (e) {
      erro(e);
    }
  }

  async function onRemoverDaBiblioteca() {
    if (!uj) return;
    try {
      await removerDaBiblioteca.mutateAsync(uj.id);
      setUj(null);
    } catch (e) {
      erro(e);
    }
  }

  if (isLoading) {
    return <Center mih={300}><Loader /></Center>;
  }
  if (!jogo) return null;

  return (
    <Stack gap="lg">
      <Button variant="subtle" color="gray" leftSection={<IconArrowLeft size={16} />} onClick={() => navigate(-1)} w="fit-content" px={0}>
        Voltar
      </Button>

      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 280px) 1fr', gap: 36 }}>
        <div style={{ position: 'sticky', top: 90, borderRadius: 12, overflow: 'hidden', border: '1px solid var(--mantine-color-dark-4)', aspectRatio: '3/4', height: 'fit-content' }}>
          {jogo.capaUrl ? (
            <img src={jogo.capaUrl} alt={jogo.nome} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
          ) : (
            <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 18, textAlign: 'center', background: corFundo(jogo.nome) }}>
              <Text fw={800} fz={20} c="white">{jogo.nome}</Text>
            </div>
          )}
        </div>

        <div>
          <Title order={1}>{jogo.nome}</Title>
          <Group gap={8} mt="sm" mb={4}>
            {jogo.ano && <Text c="dimmed">{jogo.ano}</Text>}
            {jogo.generos.map((g) => <Badge key={g} variant="light">{g}</Badge>)}
            {!!jogo.metacritic && <Badge color="lime" variant="filled">Metacritic {jogo.metacritic}</Badge>}
          </Group>

          {jogo.plataformasDisponiveis.length > 0 && (
            <Group gap={6} mb={4}>
              <Text size="xs" c="dimmed">Disponível em:</Text>
              {jogo.plataformasDisponiveis.map((p) => <Badge key={p} variant="outline" size="sm">{p}</Badge>)}
            </Group>
          )}

          {jogo.tempoMedioHoras && (
            <Text size="xs" c="dimmed" mb={4}>Tempo médio pra zerar (comunidade): {jogo.tempoMedioHoras}h</Text>
          )}

          {jogo.dlcs.length > 0 && (
            <Group gap={6} mt={4}>
              <Text size="xs" c="dimmed">DLCs:</Text>
              {jogo.dlcs.map((d) => (
                <Badge key={d.id} variant="dot" size="sm" style={{ cursor: 'pointer' }} onClick={() => navigate(`/jogo/${d.id}`)}>
                  {d.nome}
                </Badge>
              ))}
            </Group>
          )}

          <Stack gap={10} mt="xl">
            <Text fw={700}>Status</Text>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 10 }}>
              {STATUS_LISTA.map((s) => (
                <button
                  key={s.valor}
                  onClick={() => definirStatus(s.valor)}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 9,
                    background: uj?.status === s.valor ? `${s.cor}26` : 'var(--mantine-color-dark-6)',
                    border: `1px solid ${uj?.status === s.valor ? s.cor : 'var(--mantine-color-dark-4)'}`,
                    color: 'var(--mantine-color-white)', borderRadius: 12, padding: '12px 14px',
                    fontSize: 14, fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit',
                  }}
                >
                  <StatusIcon status={s.valor} size={16} /> {s.label}
                </button>
              ))}
            </div>
          </Stack>

          {uj ? (
            <>
              <Group mt="xl" gap={40} align="flex-start">
                <div>
                  <Text fw={700} mb={10}>Sua nota</Text>
                  <Group gap={5}>
                    {DEZ.map((n) => (
                      <button
                        key={n}
                        onClick={() => setNota(n)}
                        style={{
                          width: 30, height: 34, borderRadius: 8,
                          background: (uj.nota ?? 0) >= n ? '#f5c518' : 'var(--mantine-color-dark-6)',
                          border: `1px solid ${(uj.nota ?? 0) >= n ? '#f5c518' : 'var(--mantine-color-dark-4)'}`,
                          color: (uj.nota ?? 0) >= n ? '#1a1a1a' : 'var(--mantine-color-dimmed)',
                          cursor: 'pointer', fontWeight: 700, fontFamily: 'inherit',
                        }}
                      >
                        {n}
                      </button>
                    ))}
                    {!!uj.nota && (
                      <Button variant="subtle" color="gray" size="compact-xs" onClick={() => setNota(0)}>limpar</Button>
                    )}
                  </Group>
                </div>
                <div>
                  <Text fw={700} mb={10}>Favorito</Text>
                  <ActionIcon
                    size={50}
                    radius={12}
                    variant={uj.favorito ? 'light' : 'default'}
                    color={uj.favorito ? 'red' : 'gray'}
                    onClick={toggleFavorito}
                  >
                    {uj.favorito ? <IconHeartFilled size={20} /> : <IconHeart size={20} />}
                  </ActionIcon>
                </div>
              </Group>

              <Stack gap={10} mt="xl">
                <Text fw={700}>Resenha</Text>
                <Textarea
                  minRows={3}
                  autosize
                  placeholder="O que você achou desse jogo?"
                  value={resenha}
                  onChange={(e) => setResenha(e.currentTarget.value)}
                  onBlur={salvarResenha}
                />
              </Stack>

              <Stack gap={14} mt="xl">
                <Group justify="space-between">
                  <Text fw={700}>Suas jogatinas</Text>
                  <Button variant="subtle" size="compact-sm" leftSection={<IconPlus size={14} />} onClick={abrirDialog}>
                    Registrar
                  </Button>
                </Group>

                {uj.jogatinas.length === 0 ? (
                  <Text c="dimmed" size="sm">Nenhuma jogatina registrada. Marque quando e onde você jogou — inclusive rejogadas.</Text>
                ) : (
                  <Stack gap={10}>
                    {uj.jogatinas.map((jt) => {
                      const info = statusInfo(jt.status);
                      return (
                        <Group key={jt.id} gap={13} p={14} style={{ background: 'var(--mantine-color-dark-7)', border: '1px solid var(--mantine-color-dark-4)', borderRadius: 12 }}>
                          <Center w={36} h={36} style={{ borderRadius: 9, background: `${info.cor}26`, flexShrink: 0 }}>
                            <StatusIcon status={jt.status} size={18} />
                          </Center>
                          <div style={{ flex: 1 }}>
                            <Text size="sm" fw={600}>{jt.plataforma || 'Plataforma não informada'}</Text>
                            <Text size="xs" c="dimmed">
                              {info.label}
                              {jt.ano ? ` · ${jt.ano}` : ''}
                              {jt.horas ? ` · ${jt.horas}h` : ''}
                              {jt.ehRejogada ? ' · rejogada' : ''}
                            </Text>
                          </div>
                          {jt.ehRejogada && <IconRepeat size={16} opacity={0.6} />}
                          <ActionIcon variant="subtle" color="gray" onClick={() => onRemoverJogatina(jt.id)}>
                            <IconTrash size={16} />
                          </ActionIcon>
                        </Group>
                      );
                    })}
                  </Stack>
                )}
              </Stack>

              <Button color="red" variant="light" leftSection={<IconTrash size={16} />} mt="lg" onClick={onRemoverDaBiblioteca}>
                Remover da biblioteca
              </Button>
            </>
          ) : (
            <Group gap={8} mt="xl" c="dimmed">
              <IconInfoCircle size={18} />
              <Text size="sm">Escolha um status acima para adicionar este jogo à sua biblioteca.</Text>
            </Group>
          )}
        </div>
      </div>

      <Modal opened={dialogAberto} onClose={() => setDialogAberto(false)} title="Registrar jogatina" centered>
        <Stack>
          <Select
            label="Plataforma"
            placeholder="Selecione"
            searchable
            data={plataformas.map((p) => ({ value: String(p.id), label: p.nome }))}
            value={form.plataformaId != null ? String(form.plataformaId) : null}
            onChange={(v) => setForm((f) => ({ ...f, plataformaId: v ? Number(v) : null }))}
          />
          <Group grow>
            <NumberInput label="Ano" placeholder="2024" value={form.ano ?? ''} onChange={(v) => setForm((f) => ({ ...f, ano: v === '' ? null : Number(v) }))} />
            <NumberInput label="Horas" placeholder="40" value={form.horas ?? ''} onChange={(v) => setForm((f) => ({ ...f, horas: v === '' ? null : Number(v) }))} />
          </Group>
          <Select
            label="Como terminou"
            data={STATUS_LISTA.map((s) => ({ value: String(s.valor), label: s.label }))}
            value={String(form.status)}
            onChange={(v) => setForm((f) => ({ ...f, status: v ? Number(v) : f.status }))}
          />
          <Checkbox
            label="Foi uma rejogada"
            checked={form.ehRejogada}
            onChange={(e) => setForm((f) => ({ ...f, ehRejogada: e.currentTarget.checked }))}
          />
          <Group justify="flex-end" mt="sm">
            <Button variant="subtle" color="gray" onClick={() => setDialogAberto(false)}>Cancelar</Button>
            <Button onClick={salvarJogatina} loading={adicionarJogatina.isPending}>Salvar</Button>
          </Group>
        </Stack>
      </Modal>
    </Stack>
  );
}
